version: "3.7"

services: 
    backend:
        tty: true
        build: 
            context: elearning_app/
            dockerfile: ./Dockerfile
            cache_from:
                - "${BACKEND_IMAGE}"
        image: "${BACKEND_IMAGE}"
        command: sh /usr/src/app/backend/start.sh
        expose:
            - 8000
        env_file:
            - .envs/.env.prod
        volumes:
            - static_volume:/usr/src/app/backend/static
            - media_volume:/usr/src/app/backend/media
        
    nginx:
        build:
            context: ./nginx
            cache_from: 
                - "${NGINX_IMAGE}"
        ports: 
            - 80:80
        depends_on: 
            - backend
            - frontend
        volumes:
            - static_volume:/usr/src/app/backend/static
            - media_volume:/usr/src/app/backend/media
    frontend:
        image: "${FRONTEND_IMAGE}"
        build: 
            context: frontend/
            dockerfile: ./Dockerfile
            cache_from: 
                - "${FRONTEND_IMAGE}"
        depends_on: 
            - backend
        expose:
            - 8080
        command: serve --single -p 8080 dist
        
volumes: 
    postgres_data:
    static_volume:
    media_volume:
    frontend:
