version: "3.7"

services:
    django: &django
        build: ./elearning_app
        volumes:
            - ./elearning_app:/usr/src/app/backend/
        env_file:
            - .envs/.env.dev

    backend:
        <<: *django
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=elearningapp
            - POSTGRES_PASSWORD=elearningapp
            - POSTGRES_DB=django_db
    frontend:
        build: 
            context: frontend/
            dockerfile: ./Dockerfile
        depends_on: 
            - backend
        ports:
            - 8080:8080
        volumes: 
            - frontend:/urs/src/app/frontend/
        command: npm run serve
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        depends_on: 
            - frontend
    celery: &celery
        <<: *django
        command: celery -A elearning_app worker --loglevel=INFO

    celery_beat: &celery_beat
        <<: *django
        command: celery -A elearning_app beat
    redis:
        image: redis:alpine



volumes: 
    postgres_data:
    frontend:
