# Generated by Django 3.1.7 on 2021-04-27 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20210329_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.question'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.category'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='course.course'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.test'),
        ),
        migrations.AlterField(
            model_name='step',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='course.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'course')},
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.participation')),
            ],
        ),
        migrations.CreateModel(
            name='TheorySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theorysessions', to='course.coursesession')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theorysessions', to='course.theory')),
            ],
            options={
                'unique_together': {('course_session', 'theory')},
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsessions', to='course.coursesession')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsessions', to='course.test')),
            ],
            options={
                'unique_together': {('course_session', 'test')},
            },
        ),
    ]
